# config.yaml
logging:
  level: INFO # DEBUG/INFO/WARNING/ERROR/CRITICAL
  file_path: data/logs/profiler.log
  max_size: 1048576 # 1MB
  backup_count: 3
  format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"

crawler:
  request_timeout: 10
  retry_attempts: 3
  user_agent: "ProfessionalProfiler/1.0 (+https://yourdomain.com)"

fuzzy:
  cutoff: 0.85
  scorer: token_sort_ratio

degree_aliases:
  Bachelor:
    - B.A
    - B.S
    - AB
    - SB
  Master:
    - M.A
    - M.S
    - MSc
  Doctor:
    - PhD
    - D.Phil
    - Dr.phil
